// utils/iconMapper.js
import {
  FaSwimmingPool,
  FaCar,
  FaWifi,
  FaCoffee,
  FaSnowflake,
  FaTv,
  FaPaw,
  FaDumbbell,
  FaUtensils,
  FaShower,
  FaHotTub,
  FaUmbrellaBeach,
  FaConciergeBell,
  FaKey,
  FaMusic,
  FaParking,
  FaMotorcycle,
  FaShoppingBag,
  FaWineBottle,
  FaWheelchair,
  FaBeer,
  FaClock,
  FaCreditCard,
  FaCalendarCheck,
  FaRestroom,
} from "react-icons/fa";
import {
  GiTacos,
  GiShrimp,
  GiFullPizza,
  GiHamburger,
  GiOakLeaf,
  GiSteak,
  GiNoodles,
  GiCupcake,
  GiParkBench,
  GiWashingMachine,
  GiTreeDoor,
  GiMeal,
} from "react-icons/gi";
import { FaStroopwafel } from "react-icons/fa6";
import { MdBalcony } from "react-icons/md";

export const iconMapper = {
  FaSwimmingPool,
  FaCar,
  FaWifi,
  FaCoffee,
  FaSnowflake,
  FaTv,
  FaPaw,
  FaDumbbell,
  FaUtensils,
  FaShower,
  FaHotTub,
  FaUmbrellaBeach,
  FaConciergeBell,
  FaKey,
  FaMusic,
  FaParking,
  FaMotorcycle,
  FaShoppingBag,
  FaWineBottle,
  FaWheelchair,
  FaBeer,
  FaClock,
  FaCreditCard,
  FaCalendarCheck,
  FaRestroom,
  GiTacos,
  GiShrimp,
  GiFullPizza,
  GiHamburger,
  GiOakLeaf,
  GiSteak,
  GiNoodles,
  GiCupcake,
  GiParkBench,
  GiWashingMachine,
  GiTreeDoor,
  GiMeal,
  FaStroopwafel,
  MdBalcony,
};
